<h2><?= $config->title ?>のテーブル情報</h2>
<?= $this->partial('common/_search_filter'); ?>

<table class="table table-hover table-striped table-bordered">
<tr>
<?php
 foreach ($config->fields as $column => $value ) {
     echo sprintf('<th>%s</th>',$value['label']);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($config->fields as $column => $no_use_value ) {
        echo sprintf('<td>%s</td>',$row->$column);
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>
