<script>
  $(function() {

    $('#btn_like').on('click', function(){
      var btn = $(this);
      var target = $('#like_numVal');
      var val = parseInt(target.text());
      $.ajax({
        type: 'POST',
        url: '',
      })
      .success(function(data){
        if(false) {
          btn.addClass('current');
          target.text(val+1);
        } else {
          btn.removeClass('current');
          target.text(val-1);
        }
      });
    });

    $('#comment_form').on('submit', function(e){
      e.preventDefault();
      var form = $(this);
      var url = form.attr('action');
      var method = form.attr('method');
      var formData = new FormData(form.get()[0]);
      $.ajax({
        type: method,
        url: url,
        data: formData,
        processData: false,
        contentType: false
      })
      .success(function(data){
        if(true) {
          $('#comment_list').prepend(data);
          exports.common.ajaxModal.on('/popup_commentComplete.html', this, event);
          formInit();
        } else {
          exports.common.ajaxModal.error();
        }
      })
      .error(function(){
        exports.common.ajaxModal.error();
      })
    })

    //フォーム初期化
    function formInit() {
      var form = $('#comment_form')
      form.find('textarea').val('')
    }

  });
</script>

<?= $this->partial('common/header') ?>

<article class="contents item_contents">

  <div class="item_img">
    <img src="/images/item/00001.png" alt="画像タイトルが入ります">
  </div>

  <div class="item_head">
    <div class="item_region">鹿児島県いちき串木野市</div>
    <h1 class="item_title">タイトルが入ります。</h1>
  </div>

  <div class="item_body">
    <div class="like">
      <div class="like_btn">
        <button type="button" id="btn_like">
          <svg role="image" class="like_icon">
            <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_like" />
          </svg>
        </button>
      </div>
      <div class="like_num">
        LIKE<span class="like_numVal" id="like_numVal">100</span>件
      </div>
    </div>

    <div class="item_detail">
      テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    </div>

    <section class="comment">
      <div class="comment_head">
        <h1 class="comment_title">
          <svg role="image" class="comment_icon">
            <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_balloon" />
          </svg>
          コメント（100）
        </h1>
      </div>

      <div class="comment_input">
        <form action="/template_comment.html" method="post" id="comment_form">
          <input type="hidden" name="id" value="1">
          <input type="hidden" name="name" value="ユーザー名が入ります">
          <textarea name="comment_textarea" placeholder="コメントを入力してください"></textarea>
          <div class="comment_btn btn">
            <button type="submit" class="btn_comment" id="comment_btn">
              コメントする
            </button>
          </div>
        </form>
      </div>

      <ul class="comment_list" id="comment_list">
        <li class="comment_listItem">
          <div class="comment_thumb">
            <img src="/images/item/00001.png">
          </div>
          <div class="comment_detail">
            <div class="comment_name">ユーザー名が入ります</div>
            <div class="comment_text">
              テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
            </div>
          </div>
        </li>
      </ul>

      <div class="comment_more">
        <a onclick="exports.common.addComment.add('/json/dummy_comment.json');">
          もっと見る
        </a>
      </div>

    </section>

  </div>

</article>

<?= $this->partial('common/postBtn') ?>
