<?= $this->partial('common/header') ?>

<div class="contents profile_contents">

  <ul class="profile_list">
    <li class="profile_listItem">
      <a href="#">
        <dl class="profile_item">
          <dt class="profile_itemKey">ユーザー名：</dt>
          <dd class="profile_itemVal">
            ユーザー名が入ります
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
    <li class="profile_listItem">
      <a href="#">
        <dl class="profile_item">
          <dt class="profile_itemKey">メールアドレス：</dt>
          <dd class="profile_itemVal">
            abcdefghijklmnopqrstuvwxyz@abcdefghijklmnopqrstuvwxyz.jp
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
    <li class="profile_listItem">
      <a href="#">
        <dl class="profile_item">
          <dt class="profile_itemKey">パスワード：</dt>
          <dd class="profile_itemVal">
            ********
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
    <li class="profile_listItem">
      <a href="/">
        <dl class="profile_item">
          <dt class="profile_itemKey">投稿数：</dt>
          <dd class="profile_itemVal">
            9999件
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
    <li class="profile_listItem">
      <a href="/">
        <dl class="profile_item">
          <dt class="profile_itemKey">コメント：</dt>
          <dd class="profile_itemVal">
            9999件
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
    <li class="profile_listItem">
      <a href="/like.html">
        <dl class="profile_item">
          <dt class="profile_itemKey">お気に入り：</dt>
          <dd class="profile_itemVal">
            9999件
            <svg role="image" class="profile_arrow">
              <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
            </svg>
          </dd>
        </dl>
      </a>
    </li>
  </ul>

  <div class="profile_btn btn">
    <a href="#">ログアウト</a>
  </div>


</div>

<?= $this->partial('common/postBtn') ?>
