<?= $this->partial('common/header') ?>

<div class="contents">

  <div class="search">
    <form action="" method="get" class="search_form">
      <input type="search" name="search_input" id="search_input" class="search_input">
      <label for="search_input">
        <svg role="image" class="search_icon">
          <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_search" />
        </svg>
        キーワードでさがす
      </label>
    </form>
  </div>

  <div class="list_head">
    <div class="list_headKey">#検索文言</div>
    <div class="list_headval">15件</div>
  </div>

  <div class="sort">
    <ul class="sort_btnList">
      <li class="sort_btn">
        <a href="#">新着順</a>
      </li>
      <li class="sort_btn">
        <a class="current">お気に入り順</a>
      </li>
    </ul>
  </div>

  <ul class="list" id="item_list">
    <li class="list_item">
      <a href="/detail.html?id=">
        <div class="list_thumb">
          <img src="/images/item/00001.png" alt="">
        </div>
      </a>
    </li>
    <li class="list_item">
      <a href="/detail.html?id=">
        <div class="list_thumb">
          <img src="/images/item/00001.png" alt="">
        </div>
      </a>
    </li>
    <li class="list_item">
      <a href="/detail.html?id=">
        <div class="list_thumb">
          <img src="/images/item/00001.png" alt="">
        </div>
      </a>
    </li>
  </ul>

  <div class="list_more">
    <a onclick="exports.common.addItem.add('/json/dummy_item.json', $('#item_list'));">もっと読み込む</a>
  </div>

</div>

<?= $this->partial('common/postBtn') ?>
