<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>ごちぽんAPI</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="robots" content="noindex">
    <meta http-equiv="Content-Style-Type" content="text/css">
    <link href="/css/base.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>

  </head>
  <body>

<?php

 echo $this->getContent();
?>
  </body>
</html>
