<!DOCTYPE html>
<html lang="ja">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
  <meta charset="utf-8">
  <meta name="robots" content="INDEX,FOLLOW">
  <title>お宝ログ</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <link href="/css/base.css" rel="stylesheet" type="text/css">
  <script src="http://code.jquery.com/jquery-2.2.2.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/js/common.js"></script>
  <script>
    (function(){
      $(exports.common.Ready);
    })();
  </script>

  </head>
  <body>
<div class="wrapper">

<?php

 echo $this->getContent();
?>
</div>
  </body>
</html>
