<h2>営業用ページ</h2>
     <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">検索</button>

 <?= $this->partial('/sales/_search_filter'); ?>
<table style="width:auto;" class="alt-table-responsive table-striped table-bordered">
<tr>
<?php
 foreach ($columns as $column => $value ) {
     echo sprintf('<th class="col-md-6">%s</th>',$column);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($columns as $column => $methods ) {
        $getModel = $methods['model'];
        $column = $methods['column'];
        if ($getModel == 'product') {
            $text = $row->$column;
        } else {
            $text = '';
            if ($row->$getModel) {
                $text = $row->$getModel->$column;
            }
        }
        $popoverId = $getModel.'_'.$column.'_'.$row->id;

?>
<td>
     <?php if (strpos($text, '<') === false) { ?>
<a id="<?= $popoverId ?>" class="btn" href="#" data-content="<?= $text ?>" rel="popover" data-placement="bottom" data-original-title="<?= $column ?>" data-trigger="hover"><?= $this->tag->trimMessage($text) ?></a>
     <?php
         } else {
          echo $text;
        }

      ?>

</td>

<script>


     <?php
     echo sprintf("$('#%s').popover();", $popoverId);
     ?>
</script>
<?php
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>
