<div class="modal_dialog modal_dialog-vCenter">
  <div class="modal_contents">
    <div class="modal_close">
      <a data-dismiss="modal" aria-label="Close">
        <svg role="image" class="modal_closeIcon">
          <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_close" />
        </svg>
      </a>
    </div>

    <div class="modal_text">
      お宝を投稿しました。<br>
      投稿したお宝は、投稿一覧から確認できます。
    </div>

  </div>
</div>
