<? $i = 0; ?>
<? foreach ($_POST['data'] as $key1 => $value1) { ?>
  <? foreach ($value1 as $key2 => $value2) { ?>
    <!--<?=var_dump($key2)?>-->
    <!--<?=var_dump($value2)?>-->
    <? foreach ($value2 as $key3 => $value3) { ?>
      <li class="regionList_item">
        <label class="region_label" for="radio_search-<?=$i+1?>">
          <?=$key2.$value3?>
          <input type="radio" name="radio_search" id="radio_search-<?=$i+1?>" value="<?=$key2.$value3?>">
          <svg role="image" class="region_arrow">
            <use xlink:href="<?= $this->tag->urlForImage('svg/icons.svg') ?>#icon_arrow" />
          </svg>
        </label>
      </li>
      <? $i++; ?>
    <? } ?>
  <? } ?>
<? } ?>
