<h2>営業用ページ</h2>

<div class="form-horizontal">
<?php
     echo $this->tag->form('');

foreach ($searchFilter as $field => $label ) : ?>
    <div class="form-group">
    <div class="col-xs-5"><label><?= $label; ?></label></div>
    <div class="col-xs-2">

<?php if (strpos($field, 'id') === false) { ?>
    <input type="text" class="form-control" name="search[<?= $field ?>]" value="
<?= isset($searchDatas[$field]) ? htmlspecialchars($searchDatas[$field]) : ''; ?>
">

<?php
   } else {
    echo sprintf('<select class="form-control" name="search[%s]">', $field);
    if ($field == 'customer_id') {
        foreach ($customerNames as $customerId => $customerName) {
            echo sprintf('<option value="%s">%s</option>', $customerId, $customerName);
        }
    } else {
        foreach ($memberNames as $memberId => $memberName) {
            echo sprintf('<option value="%s">%s</option>', $memberId, $memberName);
        }
    }
    echo '</select>';
}
?>

    </div>
    </div>
<? endforeach; ?>

    <div class="form-group">
    <div class="col-xs-5"></div>
    <div class="col-xs-2">
    <button type="submit" class="btn btn-primary">検索</button>
    </div>
    </div>
</form>
</div>


<table style="width:auto;" class="alt-table-responsive table-striped table-bordered">
<tr>
<?php
 foreach ($columns as $column => $value ) {
     echo sprintf('<th class="col-md-6">%s</th>',$column);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($columns as $column => $methods ) {
        $getModel = $methods['model'];
        $column = $methods['column'];
        if ($getModel == 'sales_history') {
            $text = $row->$column;
        } elseif ($getModel == 'dummy') {
            $text = 'dummy';
        } else {
            $text = '';
            if ($row->$getModel) {
                $text = $row->$getModel->$column;
            }
        }
        $popoverId = $getModel.'_'.$column.'_'.$row->id;

?>
<td>
     <?php if (strpos($text, '<') === false) { ?>
<a id="<?= $popoverId ?>" class="btn" href="#" data-content="<?= $text ?>" rel="popover" data-placement="bottom" data-original-title="<?= $column ?>" data-trigger="hover"><?= $this->tag->trimMessage($text) ?></a>
     <?php
         } else {
          echo $text;
        }

      ?>

</td>

<script>


     <?php
     echo sprintf("$('#%s').popover();", $popoverId);
     ?>
</script>
<?php
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>
