<?php
/**
 * レポート画面で当選者リスト/コメント一覧を表示する部分
 */
?>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 style="font-size:20px;font-weight:bold;"><?= $panelHeadline ?></h3>
        </div>
        <div class="panel-body">
<table class="table table-striped table-bordered">
<thead class="thead-inverse"><tr>
<?php
 foreach ($fields as $label ) {
     echo sprintf('<th>%s</th>',$label);
 }
?>
</tr></thread>
<?php
    foreach ( $list as $id => $value ) {

        $checkedData = (isset($publishData[$checkBoxLabel]) && isset($publishData[$checkBoxLabel][$id]));

        //checkのfieldがない場合は公開用なので、データがなければなにも表示しない
        if (!isset($fields['check']) && !$checkedData) {
                continue;
        }

        echo '<tr>';
        foreach ($fields as $key => $no_use_value ) {
            if ($key !== 'check') {

                echo sprintf('<td>%s</td>',$value[$key]);
                continue;
            }
            $checked = $checkedData ? 'checked' :'';
            echo sprintf('<td><input type="checkbox" name="%s[%d]" value="%d" %s></td>',
                         $checkBoxLabel,$id,$id,$checked);
        }
        echo '</tr>';
    }
?>
</table>
        </div>
    </div>
</div>
