<div class="container">
     <?= $this->tag->form('/member/login'); ?>

     <fieldset class="form-group">
     <label>ユーザID</label>
     <input type="mail" class="form-control" id="loginId" name="loginId" placeholder="" />
     </fieldset>

     <fieldset class="form-group">
     <label>パスワード</label>
     <input type="password" class="form-control" id="password" name="password" />
     </fieldset>

     <button type="submit" class="btn btn-primary">Submit</button>
     </form>
 </div>
