<h2><?= $product->name ?>の<?= $reference->tool_table_label ?></h2>

<table class="table table-striped table-bordered">
<?php
    foreach ($productConfig->fields as $column => $value ) {
    echo '<tr>';
    echo sprintf('<td>%s</td><td>%s</td>',$value['label'],$product->$column);
    echo '</tr>';

    }
?>
</table>


<h2><?= $reference->tool_table_label ?>データ一覧 <?= $reference->tool_create_data_button; ?></h2>

<table class="table table-hover table-striped table-bordered">
<tr>
<?php
 foreach ($fields as $label ) {
     echo sprintf('<th>%s</th>',$label);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($fields as $column => $no_use_value ) {
        echo sprintf('<td>%s</td>',$row->$column);
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>
