
<h2><?= $customer->name ?>様の商品情報
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">検索</button>
</h2>

     <?= $this->partial('common/_search_filter_modal'); ?>

<table class="table table-hover table-striped table-bordered">
<tr>
<?php
 foreach ($fields as $column => $label ) {
     echo sprintf('<th>%s</th>',$label);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($fields as $column => $no_use_value ) {
        echo sprintf('<td>%s</td>',$row->$column);
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>
