<h2>承認待ち一覧</h2>
<?php

foreach ($tables as $tableName => $tableData) {
    echo $this->tag->linkTo(['?table='.$tableName, $tableData['label'],
                             'class' => "btn btn-primary"]);
    echo ' ';
}
?>
<div class="spacer20"></div>
<? if (isset($paginator)) : ?>
<table style="width:auto;" class="alt-table-responsive table-striped table-bordered">
<tr>
<?php
 foreach ($columns as $column => $value ) {
     echo sprintf('<th class="col-md-6">%s</th>',$column);
 }
?>
</tr>
<?php if ( $paginator->getTotal() == 0 ): ?>
<tr><td>データがありません</td></tr>
<?php else: ?>

<?php
foreach ( $paginator->getResult() as $row ) {
    echo '<tr>';
    foreach ($columns as $column => $methods ) {
        $getModel = $methods['model'];
        $column = $methods['column'];
        if ($getModel == $table || $getModel == 'own') {
            $text = $row->$column;
        } else {
            $text = '';
            if ($row->$getModel) {
                $text = $row->$getModel->$column;
            }
        }
        $popoverId = $getModel.'_'.$column.'_'.$row->id;

?>
<td>
     <?php if (strpos($text, '<') === false) { ?>
<?= $text ?>
     <?php
         } else {
          echo $text;
        }

      ?>

</td>
<?php
    }
    echo '</tr>';
}
     endif;
?>
</table>
<?= $this->partial('common/_paginate'); ?>

     <? endif; ?>